# Generated by Django 5.2.4 on 2025-07-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_user_id_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleteuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
