# Generated by Django 5.2.4 on 2025-07-16 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_deleteuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
