# Generated by Django 5.2.4 on 2025-07-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_deleteuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleteuser',
            old_name='user',
            new_name='user_id',
        ),
    ]
