# Generated by Django 5.2.4 on 2025-07-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_user_deleteuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleteuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
